doctrine:
    dbal:
        dbname: '%env(DB_NAME)%'
        host: 'chat-platform_mysql'
        port: 3306
        user: '%env(DB_USER)%'
        password: '%env(DB_PASS)%'
        driver: pdo_mysql
        charset: UTF8
        server_version: '5.6'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        types:
            email: App\Doctrine\Types\EmailType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
